import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";
import animate from "tailwindcss-animate";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        "surface-container": "#171f33",
        "surface-tint": "#d2bbff",
        surface: "#0b1326",
        "tertiary-fixed": "#acedff",
        "slate-800": "#1E293B",
        "tertiary-fixed-dim": "#4cd7f6",
        "electric-orange": "#FB923C",
        primary: "#d2bbff",
        "neon-purple": "#A78BFA",
        "inverse-primary": "#732ee4",
        "on-secondary": "#4f2500",
        "cyan-glitter": "#22D3EE",
        "on-secondary-container": "#451f00",
        error: "#ffb4ab",
        "tertiary-container": "#007184",
        "surface-container-low": "#131b2e",
        "on-primary": "#3f008e",
        "on-tertiary": "#003640",
        "outline-variant": "#4a4455",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "on-tertiary-container": "#b7efff",
        "surface-dim": "#0b1326",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-surface-variant": "#ccc3d8",
        "error-container": "#93000a",
        "surface-indigo": "#1E1B4B",
        secondary: "#ffb783",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#ffdcc5",
        "surface-container-high": "#222a3d",
        "on-primary-container": "#ede0ff",
        "slate-900": "#0F172A",
        "on-secondary-fixed": "#301400",
        "secondary-container": "#d97722",
        "on-primary-fixed-variant": "#5a00c6",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "primary-fixed-dim": "#d2bbff",
        "primary-container": "#7c3aed",
        "glass-border": "rgba(255, 255, 255, 0.1)",
        "primary-fixed": "#eaddff",
        "surface-container-lowest": "#060e20",
        "surface-bright": "#31394d",
        "inverse-surface": "#dae2fd",
        "on-primary-fixed": "#25005a",
        tertiary: "#4cd7f6",
        "on-secondary-fixed-variant": "#713700",
        outline: "#958da1",
        "on-error": "#690005",
        "secondary-fixed-dim": "#ffb783",
        "inverse-on-surface": "#283044",
        "on-tertiary-fixed": "#001f26",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        unit: "8px",
        "margin-mobile": "16px",
        "section-gap": "80px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Lexend", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Lexend", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "headline-md": ["Lexend", "sans-serif"],
        "display-lg-mobile": ["Lexend", "sans-serif"],
        "headline-lg": ["Lexend", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": [
          "64px",
          { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [forms, containerQueries, animate],
};

export default config;
